import { z } from "zod";
export const filterSettingsSchema = z.object({
  name: z.string().trim().min(1).max(120),
  fontSize: z.number().int().min(18).max(45),
  rareColor: z.string().regex(/^#[0-9a-f]{6}$/i),
  showNormal: z.boolean(),
  showMagic: z.boolean(),
  sounds: z.boolean(),
});
export type FilterSettings = z.infer<typeof filterSettingsSchema>;
export const defaultFilterSettings: FilterSettings = {
  name: "My PoE2 filter",
  fontSize: 40,
  rareColor: "#e9b56c",
  showNormal: false,
  showMagic: true,
  sounds: true,
};
export function generateFilter(input: FilterSettings): string {
  const s = filterSettingsSchema.parse(input);
  const rgb = s.rareColor
    .slice(1)
    .match(/.{2}/g)!
    .map((x) => parseInt(x, 16))
    .join(" ");
  return `# ${s.name.replace(/[\r\n]/g, " ")} — generated by Exile Atlas\n# Path of Exile 2\n\nShow\n    Rarity == Unique\n    SetTextColor 175 96 37\n    SetBorderColor 175 96 37\n    SetFontSize 45\n${s.sounds ? "    PlayAlertSound 6 200\n" : ""}\nShow\n    Class == \"Currency\"\n    SetTextColor 170 158 130\n    SetBorderColor 170 158 130\n    SetFontSize ${s.fontSize}\n\nShow\n    Rarity == Rare\n    SetTextColor ${rgb}\n    SetBorderColor ${rgb}\n    SetFontSize ${s.fontSize}\n\n${s.showMagic ? "Show" : "Hide"}\n    Rarity == Magic\n    SetTextColor 136 136 255\n    SetFontSize 32\n\n${s.showNormal ? "Show" : "Hide"}\n    Rarity == Normal\n    SetFontSize 28\n`;
}
export function validateFilter(text: string): { valid: boolean; issues: string[] } {
  const issues: string[] = [];
  let block = false;
  if (!text.trim()) issues.push("The filter is empty");
  if (text.length > 1_000_000) issues.push("Filter must be smaller than 1 MB");
  text.split(/\r?\n/).forEach((line, index) => {
    const clean = line.trim();
    if (!clean || clean.startsWith("#")) return;
    if (/^(Show|Hide|Minimal)(\s|$)/.test(clean)) {
      block = true;
      return;
    }
    if (!block) issues.push(`Line ${index + 1}: add a Show or Hide block first`);
    const size = clean.match(/^SetFontSize\s+(\d+)/);
    if (size && (Number(size[1]) < 18 || Number(size[1]) > 45))
      issues.push(`Line ${index + 1}: font size must be 18–45`);
    if ((clean.match(/(?<!\\)"/g)?.length ?? 0) % 2)
      issues.push(`Line ${index + 1}: unclosed quotation mark`);
  });
  return { valid: issues.length === 0, issues };
}
